const option = [
    { value: "angular", label: "Angular" },
    { value: "android", label: "Android" },
    { value: "arduino", label: "Arduino" },
    { value: "bootstrape", label: "Bootstrape" },
    { value: "c++", label: "C++" },
    { value: "css", label: "CSS" },
    { value: "nodeJS", label: "Node.Js" },
    { value: "javascript", label: "JavaScript" },
    { value: "php", label: "PHP" },
    { value: "python", label: "Python" },
    { value: "react", label: "React.Js" },
    { value: "dark", label: "dark" },
    { value: "django", label: "Django" },
    { value: "docker", label: "Docker Compose" },
    { value: "flutter", label: "Flutter" },
    { value: "git", label: "Git" },
    { value: "github", label: "GitHub" },
    { value: "graphql", label: "GraphQL" },
    { value: "hasura", label: "Hasura" },
    { value: "html", label: "HTML" },
    { value: "java", label: "Java" },
    { value: "kotlin", label: "Kotlin" },
    { value: "laravel", label: "Laravel" },
    { value: "mysql", label: "MySql" },
    { value: "next.js", label: "Next.Js" },
    { value: "r", label: "R" },
    { value: "shell", label: "Bash Shell" },
    { value: "sql", label: "SQL" },
    { value: "typescript", label: "TypeScript" },
    
  ];

  export default option;